---
- name: Enforcing password quality
  debug:
    msg: Modifing /etc/security/pwquality.conf, let's enforce password quality

- name: Copy /etc/security/pwquality.conf to bckp directory
  copy:
    src: /etc/security/pwquality.conf
    dest: '/root/backp_{{ date }}/pwquality.conf'
    owner: root
    group: root
    mode: '0644'

- name: Copy jinja template to /etc/security/pwquality.conf
  template:
    src: pwquality.j2
    dest: /etc/security/pwquality.conf
    group: root
    owner: root
    mode: '0644'


